import json
from datetime import datetime
from typing import Any

from app.schemas.agent_result import AgentResult
from app.schemas.inquiry import InquiryInput


def export_agent_result_json(
    result: AgentResult, inquiry_input: InquiryInput | dict[str, Any] | None = None
) -> str:
    payload = build_export_payload(result, inquiry_input)
    return json.dumps(payload, ensure_ascii=False, indent=2)


def export_demo_report_markdown(
    result: AgentResult, inquiry_input: InquiryInput | dict[str, Any] | None = None
) -> str:
    payload = build_export_payload(result, inquiry_input)
    original = payload["original_inquiry"]
    agent = payload["agent_result"]

    lines: list[str] = [
        "# Industrial Automation Inquiry Qualification Report",
        "",
        "> This report is generated by the C+ prototype for human review. It does not quote price, promise stock availability, promise lead time, or send any final reply automatically.",
        "> price, stock, and delivery time must be manually confirmed by sales staff after technical requirements are reviewed.",
        "",
        "## 1. Original Inquiry",
        "",
        f"- Source: {original.get('source') or 'Unknown'}",
        f"- Subject: {original.get('subject') or 'N/A'}",
        f"- Customer/Company: {original.get('name') or 'N/A'} / {original.get('company') or 'N/A'}",
        f"- Country: {original.get('country') or 'N/A'}",
        "",
        "```text",
        _safe_text(original.get("message") or ""),
        "```",
        "",
        "## 2. Requirement Summary",
        "",
        f"- Inquiry Type: {agent['inquiry_type']}",
        f"- Customer Intent: {agent['customer_intent']}",
        f"- Product Category: {agent['product_category']}",
        f"- Confidence Score: {agent['confidence_score']:.2f}",
        "",
        "## 3. Extracted Requirements",
        "",
        "```json",
        json.dumps(agent["extracted_requirements"], ensure_ascii=False, indent=2),
        "```",
        "",
        "## 4. Missing Information",
        "",
    ]

    lines.extend(_bullet_list(agent["missing_information"], empty_text="No critical missing information detected."))

    lines.extend(["", "## 5. Candidate Products", ""])
    if agent["matched_products"]:
        for item in agent["matched_products"]:
            lines.extend(
                [
                    f"- {item['product_name']} (`{item['product_id']}`)",
                    f"  - Category: {item['category']}",
                    f"  - Match Score: {item['match_score']}",
                    f"  - Match Reason: {_safe_text(item['match_reason'])}",
                    f"  - Missing Confirmations: {', '.join(item.get('missing_confirmations') or []) or 'None'}",
                ]
            )
    else:
        lines.append("- No candidate product found. Manual review is required.")

    lines.extend(["", "## 6. Clarification Questions", ""])
    lines.extend(_bullet_list(agent["clarification_questions"], empty_text="No clarification questions generated."))

    lines.extend(
        [
            "",
            "## 7. English Reply Draft",
            "",
            "```text",
            _safe_text(agent["english_reply_draft"]),
            "```",
            "",
            "## 8. Risk Flags",
            "",
        ]
    )
    lines.extend(_bullet_list(agent["risk_flags"], empty_text="No risk flags generated."))

    lines.extend(["", "## 9. Retrieved Knowledge Sources", ""])
    if agent["retrieved_knowledge"]:
        for item in agent["retrieved_knowledge"][:3]:
            metadata = item.get("metadata", {})
            lines.extend(
                [
                    f"- {metadata.get('source_file', 'unknown')} / {metadata.get('section_title', 'section')}",
                    f"  - Score: {item.get('score', 0)}",
                    f"  - Preview: {_preview(item.get('content', ''))}",
                ]
            )
    else:
        lines.append("- No knowledge source retrieved.")

    lines.extend(["", "## 10. Agent Execution Trace", ""])
    if agent["agent_trace"]:
        for trace in agent["agent_trace"]:
            lines.append(
                f"- {trace['step_name']} | mode={trace['mode']} | success={trace['success']} | latency_ms={trace['latency_ms']} | {trace['output_summary']}"
            )
    else:
        lines.append("- No execution trace recorded.")

    lines.extend(
        [
            "",
            "## Sales Follow-up Suggestion",
            "",
            _safe_text(agent["sales_follow_up_suggestion"]),
            "",
        ]
    )

    return "\n".join(lines)


def build_export_payload(
    result: AgentResult, inquiry_input: InquiryInput | dict[str, Any] | None = None
) -> dict[str, Any]:
    original_inquiry = _inquiry_to_dict(inquiry_input)
    return {
        "exported_at": datetime.now().isoformat(timespec="seconds"),
        "original_inquiry": original_inquiry,
        "agent_result": result.model_dump(mode="json"),
        "disclaimer": (
            "C+ prototype output for human review only. No automatic quotation, stock promise, lead-time promise, or automatic email sending."
        ),
    }


def get_export_timestamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _inquiry_to_dict(
    inquiry_input: InquiryInput | dict[str, Any] | None,
) -> dict[str, Any]:
    if inquiry_input is None:
        return {}
    if isinstance(inquiry_input, InquiryInput):
        return inquiry_input.model_dump(mode="json")
    return dict(inquiry_input)


def _bullet_list(items: list[str], *, empty_text: str) -> list[str]:
    if not items:
        return [f"- {empty_text}"]
    return [f"- {_safe_text(item)}" for item in items]


def _preview(text: str, limit: int = 220) -> str:
    compact = " ".join(_safe_text(text).split())
    if len(compact) <= limit:
        return compact
    return compact[: limit - 3] + "..."


def _safe_text(value: Any) -> str:
    text = str(value or "")
    # Avoid leaking accidental secret-shaped strings in exported demo artifacts.
    redacted = text.replace("OPENAI_API_KEY", "OPENAI_API_KEY_REDACTED")
    if "sk-" in redacted:
        parts = redacted.split("sk-")
        redacted = parts[0] + "sk-REDACTED" + "".join(
            part[48:] if len(part) > 48 else "" for part in parts[1:]
        )
    return redacted
